# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Aiming for Truth
email: jcdavies75@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A guide to truth-seeking through science, critical thinking, and challenging the nonsense we often accept without question.
  This site is a challenge to see beyond Politics, Media and Hype.
  Learn to recognise bullshit by discovering the power of reliable evidence.
  A guide for "How to Think" not "What to Think".
  How should important decisions be made?
  Case Studies explore how policy and other decisions should and could be approached.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
#plugins:
#  - jekyll-feed

markdown: kramdown
highlighter: rouge
permalink: pretty
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed


collections:
  guide:
    output: true
    permalink: /guide/:path/
  casestudies:
    output: true
    permalink: /casestudies/:path/
  articles:
    output: true
    permalink: /articles/:path/
  

defaults:

  
  - scope:
      path: "_posts"
    values:
      layout: post
      section: posts
      heading: "Blog Posts"

  

  - scope:
      path: "_guide"
    values:
      layout: "page"
      section: "guide"
      heading: "Thinking Guide"
      intro: "Test guide intro"
      permalink: /guide/:path

  - scope:
      path: "_casestudies"
    values:
      layout: "page"
      section: "casestudies"
      heading: "Case Studies"
      intro: "Test case studies intro"
      permalink: /casestudies/:path

  - scope:
      path: "_articles"
    values:
      layout: "page"
      section: "articles"
      heading: "Asides and Tangents"
      permalink: /articles/:path
  
 
  



sass:
  sass_dir: _sass
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

liquid:
  error_mode: lax
  # For BUILD:
  #error_mode: strict
  #strict_variables: true
  #strict_filters: true
